// export.js — LintMail v0.5
// PDF (via browser print API) and Markdown export

/**
 * Export report as Markdown string
 */
export function exportMarkdown(report, providers, lang = "en") {
  const L = {
    en: { title:"LintMail Audit Report", score:"Overall Score", category:"Category",
          rules:"Rules", generated:"Generated", campaign:"Campaign Type",
          size:"HTML Size", providers:"Email Client Compatibility",
          issue:"Issue", pass:"PASS", warn:"WARN", fail:"FAIL",
          above:"↑ above avg", average:"→ on par", below:"↓ below avg" },
    pt: { title:"Relatório de Auditoria LintMail", score:"Pontuação Geral", category:"Categoria",
          rules:"Regras", generated:"Gerado em", campaign:"Tipo de Campanha",
          size:"Tamanho HTML", providers:"Compatibilidade com Clientes de Email",
          issue:"Problema", pass:"OK", warn:"ATENÇÃO", fail:"FALHA",
          above:"↑ acima da média", average:"→ na média", below:"↓ abaixo da média" },
  }[lang];

  const CAT_LABELS = {
    en: { accessibility:"Accessibility", deliverability:"Deliverability",
          bestPractices:"Best Practices", compatibility:"Compatibility",
          darkMode:"Dark Mode", spam:"Spam Score" },
    pt: { accessibility:"Acessibilidade", deliverability:"Entregabilidade",
          bestPractices:"Boas Práticas", compatibility:"Compatibilidade",
          darkMode:"Dark Mode", spam:"Score de Spam" },
  }[lang];

  const PROV_LABELS = {
    en: { gmail:"Gmail", outlook:"Outlook", appleMail:"Apple Mail / iCloud", yahoo:"Yahoo Mail" },
    pt: { gmail:"Gmail", outlook:"Outlook", appleMail:"Apple Mail / iCloud", yahoo:"Yahoo Mail" },
  }[lang];

  const gradeEmoji = (s) => s >= 80 ? "🟢" : s >= 55 ? "🟡" : "🔴";
  const statusMark = (s) => s === "pass" ? `✓ ${L.pass}` : s === "warn" ? `⚠ ${L.warn}` : `✕ ${L.fail}`;

  let md = `# ${L.title}\n\n`;
  md += `**${L.score}:** ${gradeEmoji(report.overallScore)} ${report.overallScore}/100\n`;
  md += `**${L.campaign}:** ${report.campaignType}\n`;
  md += `**${L.size}:** ${report.sizeKB}KB\n`;
  md += `**${L.generated}:** ${new Date(report.generatedAt).toLocaleString()}\n`;
  if (report.esp) md += `**ESP:** ${report.esp}\n`;
  md += "\n---\n\n";

  // Category scores table
  md += `## ${L.category} Scores\n\n`;
  md += `| ${L.category} | Score |\n|---|---|\n`;
  for (const [key, result] of Object.entries(report.categories)) {
    md += `| ${gradeEmoji(result.score)} ${CAT_LABELS[key] ?? key} | ${result.score}/100 |\n`;
  }
  md += "\n";

  // Detailed rules per category
  for (const [key, result] of Object.entries(report.categories)) {
    md += `## ${CAT_LABELS[key] ?? key} — ${result.score}/100\n\n`;
    for (const rule of result.rules) {
      md += `- **[${statusMark(rule.status)}]** ${rule.name[lang]}: ${rule.detail[lang]}\n`;
    }
    md += "\n";
  }

  // Provider compatibility
  if (providers) {
    md += `## ${L.providers}\n\n`;
    md += `| Client | Score | Issues |\n|---|---|---|\n`;
    for (const [key, data] of Object.entries(providers)) {
      const issueCount = data.issues.length === 0 ? "✓ OK" : `${data.issues.length} issue(s)`;
      md += `| ${gradeEmoji(data.score)} ${PROV_LABELS[key] ?? key} | ${data.score}/100 | ${issueCount} |\n`;
    }
    md += "\n";

    for (const [key, data] of Object.entries(providers)) {
      if (data.issues.length === 0) continue;
      md += `### ${PROV_LABELS[key] ?? key}\n\n`;
      for (const issue of data.issues) {
        const sev = issue.severity === "fail" ? `✕ ${L.fail}` : `⚠ ${L.warn}`;
        md += `- **[${sev}]** ${issue.name[lang]}: ${issue.detail[lang]}\n`;
      }
      md += "\n";
    }
  }

  md += `---\n*Generated by LintMail · https://github.com/byjuliogomes92/lintmail*\n`;
  return md;
}

/**
 * Export report as styled HTML for print-to-PDF
 * Opens in a new window and triggers print dialog
 */
export function exportPDF(report, providers, lang = "en") {
  const md  = exportMarkdown(report, providers, lang);
  const gradeColor = (s) => s >= 80 ? "#1B6F3C" : s >= 55 ? "#7A5000" : "#BA1A1A";
  const statusColor = (s) => s === "pass" ? "#1B6F3C" : s === "warn" ? "#7A5000" : "#BA1A1A";
  const statusMark  = (s) => s === "pass" ? "✓" : s === "warn" ? "!" : "✕";

  const CAT_LABELS = {
    en: { accessibility:"Accessibility", deliverability:"Deliverability",
          bestPractices:"Best Practices", compatibility:"Compatibility",
          darkMode:"Dark Mode", spam:"Spam Score" },
    pt: { accessibility:"Acessibilidade", deliverability:"Entregabilidade",
          bestPractices:"Boas Práticas", compatibility:"Compatibilidade",
          darkMode:"Dark Mode", spam:"Score de Spam" },
  }[lang];

  const PROV_LABELS = {
    en: { gmail:"Gmail", outlook:"Outlook", appleMail:"Apple Mail / iCloud", yahoo:"Yahoo Mail" },
    pt: { gmail:"Gmail", outlook:"Outlook", appleMail:"Apple Mail / iCloud", yahoo:"Yahoo Mail" },
  }[lang];

  const catRows = Object.entries(report.categories).map(([key, result]) => {
    const rulesHTML = result.rules.map((r) => `
      <tr>
        <td style="color:${statusColor(r.status)};font-weight:600;font-family:monospace;width:24px">${statusMark(r.status)}</td>
        <td style="font-weight:500;padding:2px 8px">${r.name[lang]}</td>
        <td style="color:#555;font-size:11px">${r.detail[lang]}</td>
      </tr>
    `).join("");
    return `
      <div class="cat-section">
        <div class="cat-header" style="color:${gradeColor(result.score)}">
          ${CAT_LABELS[key] ?? key} — ${result.score}/100
        </div>
        <table class="rule-table"><tbody>${rulesHTML}</tbody></table>
      </div>
    `;
  }).join("");

  const provRows = providers ? Object.entries(providers).map(([key, data]) => {
    const issueHTML = data.issues.length === 0
      ? `<tr><td colspan="3" style="color:#1B6F3C">✓ No issues detected</td></tr>`
      : data.issues.map((i) => `
          <tr>
            <td style="color:${i.severity==="fail"?"#BA1A1A":"#7A5000"};font-family:monospace;width:20px">${i.severity==="fail"?"✕":"!"}</td>
            <td style="font-weight:500;padding:2px 8px">${i.name[lang]}</td>
            <td style="color:#555;font-size:11px">${i.detail[lang]}</td>
          </tr>
        `).join("");
    return `
      <div class="cat-section">
        <div class="cat-header" style="color:${gradeColor(data.score)}">
          ${PROV_LABELS[key] ?? key} — ${data.score}/100
        </div>
        <table class="rule-table"><tbody>${issueHTML}</tbody></table>
      </div>
    `;
  }).join("") : "";

  const html = `<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8"/>
  <title>LintMail Report</title>
  <style>
    body { font-family: 'IBM Plex Sans', system-ui, sans-serif; font-size: 12px; color: #1A1A18; max-width: 760px; margin: 0 auto; padding: 32px 24px; line-height: 1.5; }
    h1 { font-size: 20px; font-weight: 700; margin-bottom: 4px; }
    .meta { color: #5A5A54; font-size: 11px; margin-bottom: 24px; }
    .score-big { font-size: 40px; font-weight: 700; color: ${gradeColor(report.overallScore)}; line-height: 1; }
    .score-row { display: flex; align-items: center; gap: 16px; margin-bottom: 24px; padding: 16px; background: #F5F5F0; border-radius: 6px; }
    .score-meta { font-size: 12px; color: #5A5A54; }
    .section-title { font-size: 14px; font-weight: 700; margin: 20px 0 8px; padding-bottom: 4px; border-bottom: 2px solid #1A1A18; }
    .summary-table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
    .summary-table th { text-align: left; font-size: 10px; text-transform: uppercase; letter-spacing: .5px; color: #9A9A92; padding: 4px 8px; border-bottom: 1px solid #D8D8D0; }
    .summary-table td { padding: 6px 8px; border-bottom: 1px solid #EEEEEA; font-size: 12px; }
    .cat-section { margin-bottom: 16px; }
    .cat-header { font-size: 13px; font-weight: 700; margin-bottom: 6px; }
    .rule-table { width: 100%; border-collapse: collapse; }
    .rule-table td { padding: 4px 4px; border-bottom: 1px solid #F0F0EB; vertical-align: top; font-size: 11px; }
    .footer { margin-top: 32px; padding-top: 12px; border-top: 1px solid #D8D8D0; font-size: 10px; color: #9A9A92; }
    @media print { body { padding: 16px; } }
  </style>
</head>
<body>
  <h1>LintMail Audit Report</h1>
  <div class="meta">
    Generated: ${new Date(report.generatedAt).toLocaleString()} &nbsp;·&nbsp;
    Campaign: ${report.campaignType} &nbsp;·&nbsp;
    Size: ${report.sizeKB}KB
    ${report.esp ? ` &nbsp;·&nbsp; ESP: ${report.esp}` : ""}
  </div>

  <div class="score-row">
    <div class="score-big">${report.overallScore}</div>
    <div class="score-meta">
      <div style="font-weight:600;font-size:14px">/100 Overall Score</div>
      <div>${report.overallScore >= 80 ? "✓ Ready to send" : report.overallScore >= 55 ? "⚠ Needs attention" : "✕ Critical issues"}</div>
    </div>
  </div>

  <div class="section-title">Category Summary</div>
  <table class="summary-table">
    <thead><tr><th>Category</th><th>Score</th></tr></thead>
    <tbody>
      ${Object.entries(report.categories).map(([key, result]) => `
        <tr>
          <td>${CAT_LABELS[key] ?? key}</td>
          <td style="font-weight:600;color:${gradeColor(result.score)}">${result.score}/100</td>
        </tr>
      `).join("")}
    </tbody>
  </table>

  <div class="section-title">Detailed Rules</div>
  ${catRows}

  ${providers ? `<div class="section-title">Email Client Compatibility</div>${provRows}` : ""}

  <div class="footer">Generated by LintMail &nbsp;·&nbsp; github.com/byjuliogomes92/lintmail</div>
  <script>window.print(); window.close();</script>
</body>
</html>`;

  const win = window.open("", "_blank");
  if (win) {
    win.document.write(html);
    win.document.close();
  }
}

/**
 * Download a file with given content and filename
 */
export function downloadFile(content, filename, mimeType = "text/plain") {
  const blob = new Blob([content], { type: mimeType });
  const url  = URL.createObjectURL(blob);
  Object.assign(document.createElement("a"), { href: url, download: filename }).click();
  URL.revokeObjectURL(url);
}
